all:
  hosts:
    kube2n1:
      ansible_host: 172.16.2.1
      kubernetes_init_node: true
      proxmox_vmid: 121
    kube2n2:
      ansible_host: 172.16.2.2
      proxmox_vmid: 122
    kube2n3:
      ansible_host: 172.16.2.3
      proxmox_vmid: 123
    kube2n4:
      ansible_host: 172.16.2.4
      proxmox_vmid: 124
    kube2n5:
      ansible_host: 172.16.2.5
      proxmox_vmid: 125

flatcar:
  children:
    cluster2:

kubernetes-control-plane:
  hosts:
    kube2n1:
    kube2n2:
    kube2n3:

kubernetes-worker-nodes:
  hosts:
    kube2n4:
    kube2n5:

cluster2:
  hosts:
    kube2n1:
    kube2n2:
    kube2n3:
    kube2n4:
    kube2n5:
  vars:
    dnsDomain: cluster2.internal
    serviceSubnet: 10.2.0.0/17
    podSubnet: 10.2.128.0/17
    loadBalancerSubnet: 10.254.2.0/24
    kubernetes_version: "v1.33.2"
    controlPlaneEndpoint: "172.16.2.254"
    cluster_BGP_ASN: 64513
    cluster_BGP_peers:
      - name: fortigate
        ASN: 65000
        address: 172.16.0.1
