- name: Create cache folder
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  run_once: true
  loop:
    - ./.temp/pki
    - ./.temp/pki/etcd

- name: Pull certs # noqa: run-once command-instead-of-module
  ansible.builtin.command: rsync -a -e ssh --rsync-path 'sudo rsync' {{ ansible_user }}@{{ ansible_host }}:/etc/kubernetes/pki/{{ item }} .temp/pki/{{ item }}
  when: kubernetes_init_node
  delegate_to: localhost
  run_once: true
  changed_when: false
  loop:
    - ca.crt
    - ca.key
    - sa.key
    - sa.pub
    - front-proxy-ca.crt
    - front-proxy-ca.key
    - etcd/ca.crt
    - etcd/ca.key

- name: Create certs directory
  ansible.builtin.raw: "mkdir -p /etc/kubernetes/pki/etcd"
  when: >
    (kubernetes_init_node is not defined or kubernetes_init_node is not true)
    and 'kubernetes-control-plane' in group_names
  changed_when: true

- name: Push certs to control plane nodes # noqa: command-instead-of-module
  ansible.builtin.command: rsync -a -e ssh --rsync-path 'sudo rsync' .temp/pki/{{ item }} {{ ansible_user }}@{{ ansible_host }}:/etc/kubernetes/pki/{{ item }}
  when: >
    (kubernetes_init_node is not defined or kubernetes_init_node is not true)
    and 'kubernetes-control-plane' in group_names
  throttle: 1
  delegate_to: localhost
  changed_when: true
  loop:
    - ca.crt
    - ca.key
    - sa.key
    - sa.pub
    - front-proxy-ca.crt
    - front-proxy-ca.key
    - etcd/ca.crt
    - etcd/ca.key

- name: Wipe cache folder
  delegate_to: localhost
  ansible.builtin.file:
    path: "./.temp/pki"
    state: absent
  run_once: true
