- name: Determine cluster nodes using Kubectl # noqa: run-once[task]
  ansible.builtin.raw: /opt/bin/kubectl get nodes -o json
  when: kubernetes_init_node
  run_once: true
  changed_when: false
  register: determine_k8s_nodes
  ignore_errors: true
  become: true
  become_user: core

- name: Extract node names # noqa: run-once[task]
  ansible.builtin.set_fact:
    kubernetes_cluster_nodes: "{{ determine_k8s_nodes.stdout | from_json | json_query('items[].metadata.name') }}"
  when: determine_k8s_nodes.rc == 0
  run_once: true

- name: Dummy node names if the cluster is not initalized # noqa: run-once[task]
  ansible.builtin.set_fact:
    kubernetes_cluster_nodes: ""
  when: determine_k8s_nodes.rc != 0
  run_once: true

- name: Set fact, host is in cluster
  ansible.builtin.set_fact:
    kubernetes_in_cluster: "{{ inventory_hostname in kubernetes_cluster_nodes }}"
