apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.254.2.0/24
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: fortigate
  namespace: metallb-system
spec:
  myASN: 64513
  peerASN: 65000
  peerAddress: 172.16.0.1
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: advertisement
  namespace: metallb-system
