apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-app-autoscaler
  namespace: sample-app
  labels:
    app: sample-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-app-deployment
  minReplicas: 3
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleUp:
      policies:
        - type: Pods
          periodSeconds: 60
          value: 5
    scaleDown:
      policies:
        - type: Percent
          periodSeconds: 60
          value: 50